### ISSUE TITLE
Add support for websockets

### ISSUE THREAD

**Issue by Chilinot** [TheGrandmother/MUD#7]
Add support for websockets in the MUD, this will allow webbrowsers and other stuff to connect to the server and play the game.

**Comment by TheGrandmother** [comment]
Just read trough some of the protocol specifications. Turns out that each sent frame contains a lot of annoying data.

I think we need to re-factor the server side to actually use websockets instead of just ignoring the unneeded part of the WebSocket protocol.

Maybe this could be useful:
http://java-websocket.org/

To get native java support we would need to use Java EE7 :/

**Comment by TheGrandmother** [comment]
Update!

Node.js has support for the normal net sockets. No need to do horrible WebSocket stuff.

I think having propper websocket support would imply a complete serverside rewrite.

**Comment by Chilinot** [comment]
Nice! Marking this issue as nonfix :)
